### ISSUE TITLE
Error: cannot create vesting schedule because not sufficient tokens

### ISSUE THREAD

**Issue by seriousidea** [abdelhamidbakhta/token-vesting-contracts#10]
Thanks for the great code!

But I have a problem that makes working with this smart contract almost impossible.

I cloned this project and deployed (to BSC Testnet) both smart contracts (`Token` and `TokenVesting`) using the `deploy.js` script, successfully verified the source code of both contracts on the BscScan. After that, when the `createVestingSchedule()` method is called in the BscScan, the error `Fail with error 'TokenVesting: cannot create vesting schedule because not sufficient tokens` occurs. The reason for this error is that the `TokenVesting` contract does not have access to the tokens of the `Token` contract, because only the owner of the `Token` contract, which is a different address from which the deployment took place, has access to these tokens.

What should be done to avoid this error?

**Comment by abdelhamidbakhta** [comment]
> 

You simply need to send tokens to the token vesting contract.
It has to be filled in order to be able to create vesting.
The typical flow looks like this:
- Alice deploys a `Token`, let's say `$ALI`
- Alice deploys the `TokenVesting` with the address of `$ALI` as parameter of the constructor
- Alice sends 1000 $ALI to the deployed `TokenVesting` contract
- Alice create a vesting of 100 $ALI with Bob as the beneficiary, for a duration of 4 years, with a monthly linear vesting
- Bob can claim the available vested tokens whenever he wants

Is that more clear ?

**Comment by seriousidea** [comment]
[abdelhamidbakhta](https://github.com/abdelhamidbakhta) Thank you! I transferred all the tokens to the `TokenVesting` smart contract and now it works great.
