### ISSUE TITLE
Function/Mapping not updated

### ISSUE THREAD

**Issue by JOHNFFFEE** [abdelhamidbakhta/token-vesting-contracts#5]
Hi,
if you revoke or release a vestingScheduleId for one recipient having multiple vestings

- getVestingSchedulesCountByBeneficiary should reduce
- getVestingSchedulesCount should reduce

I was thinking to create a mapping of released and revoked and substract from the total count

**Comment by abdelhamidbakhta** [comment]
Hi. Well that depends on how you see things. Because those functions are used to iterated vestings from the frontend. But we could have getEffectiveVestingSchedulesCountByBeneficiary. However I think this filtering should be done by the Dapp rather than in the contract directly. Since this information can be deducted off chain from the data in the contract (use boolean flags to filter effective vestings), I don't think it would be relevant to add this extra complexity in the contract. What do you think ?
Also it would break the way I compute the vesting id which are a hash of the holder address concatenated with an auto incremented index.

**Comment by JOHNFFFEE** [comment]
Hi, thank you for answering so fast.
This could be an option to save gas, the contract is already complicated
BTW well done for the audit 😊

________________________________
